version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: alunos_db
    ports:
      - "3306:3306"

  api:
    build: .
    container_name: api_alunos
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
